sudo: false
language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true

install:
  - rustup component add rustfmt

script:
  - cargo fmt -- --check
  - cd noise-protocol && cargo check --no-default-features
  - cargo test --all --verbose
